

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: agriculbase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db

  api:
    build:
      context: ./ProductsService.API
      dockerfile: Docker/Dockerfile
    ports:
      - "5206:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=agriculbase;Username=user;Password=userpassword"
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      - db

  logic:
    build:
      context: ./ProductApp.BusinessLogic
      dockerfile: Dockerfile
    ports:
      - "7233:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"  
  

volumes:
  postgres-data: